// Engine Types - Structure Templates (asset path mappings)

import type { StructureTemplate, StructureType } from './structures.ts';

// Asset path constants (previously from @assets Babylon.js module)
const HexTileAssets = {
  BUILDING_MARKET: 'assets/models/hex/building-market.glb',
  BUILDING_TOWER: 'assets/models/hex/building-tower.glb',
  BUILDING_HOUSE: 'assets/models/hex/building-house.glb',
  BUILDING_CASTLE: 'assets/models/hex/building-castle.glb',
  UNIT_MANSION: 'assets/models/hex/unit-mansion.glb',
  BUILDING_FARM: 'assets/models/hex/building-farm.glb',
  BUILDING_MILL: 'assets/models/hex/building-mill.glb',
  BUILDING_MINE: 'assets/models/hex/building-mine.glb',
  BUILDING_CABIN: 'assets/models/hex/building-cabin.glb',
  UNIT_HOUSE: 'assets/models/hex/unit-house.glb',
} as const;

const MechanicalAssets = {
  HOUSE_SMALL: 'assets/models/mechanical/house-small.glb',
} as const;

const StructureAssets = {
  WATER_TOWER: 'assets/models/structures/watertower.glb',
  WELL: 'assets/models/structures/well.glb',
  FENCE: 'assets/models/structures/fence.glb',
  RAIL: 'assets/models/structures/rail.glb',
} as const;

export const STRUCTURE_TEMPLATES: Record<StructureType, StructureTemplate> = {
  saloon: {
    type: 'saloon',
    name: 'Saloon',
    width: 12,
    depth: 10,
    height: 6,
    hasInterior: true,
    entranceOffset: { x: 0, z: 5 },
    modelPath: HexTileAssets.BUILDING_MARKET,
  },
  sheriff_office: {
    type: 'sheriff_office',
    name: 'Sheriff Office',
    width: 8,
    depth: 8,
    height: 5,
    hasInterior: true,
    entranceOffset: { x: 0, z: 4 },
    modelPath: HexTileAssets.BUILDING_TOWER,
  },
  general_store: {
    type: 'general_store',
    name: 'General Store',
    width: 10,
    depth: 8,
    height: 5,
    hasInterior: true,
    entranceOffset: { x: 0, z: 4 },
    modelPath: HexTileAssets.BUILDING_HOUSE,
  },
  bank: {
    type: 'bank',
    name: 'Bank',
    width: 10,
    depth: 10,
    height: 6,
    hasInterior: true,
    entranceOffset: { x: 0, z: 5 },
    modelPath: HexTileAssets.BUILDING_CASTLE,
  },
  hotel: {
    type: 'hotel',
    name: 'Hotel',
    width: 12,
    depth: 10,
    height: 8,
    hasInterior: true,
    entranceOffset: { x: 0, z: 5 },
    modelPath: HexTileAssets.UNIT_MANSION,
  },
  stable: {
    type: 'stable',
    name: 'Stable',
    width: 14,
    depth: 8,
    height: 5,
    hasInterior: false,
    entranceOffset: { x: 0, z: 4 },
    modelPath: HexTileAssets.BUILDING_FARM,
  },
  water_tower: {
    type: 'water_tower',
    name: 'Water Tower',
    width: 4,
    depth: 4,
    height: 12,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0 },
    modelPath: StructureAssets.WATER_TOWER,
  },
  windmill: {
    type: 'windmill',
    name: 'Windmill',
    width: 3,
    depth: 3,
    height: 10,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0 },
    modelPath: HexTileAssets.BUILDING_MILL,
  },
  mine_entrance: {
    type: 'mine_entrance',
    name: 'Mine Entrance',
    width: 6,
    depth: 4,
    height: 4,
    hasInterior: false,
    entranceOffset: { x: 0, z: 2 },
    modelPath: HexTileAssets.BUILDING_MINE,
  },
  train_station: {
    type: 'train_station',
    name: 'Train Station',
    width: 16,
    depth: 6,
    height: 5,
    hasInterior: true,
    entranceOffset: { x: 0, z: 3 },
    modelPath: MechanicalAssets.HOUSE_SMALL,
  },
  house_small: {
    type: 'house_small',
    name: 'Small House',
    width: 6,
    depth: 6,
    height: 4,
    hasInterior: true,
    entranceOffset: { x: 0, z: 3 },
    modelPath: HexTileAssets.BUILDING_CABIN,
  },
  house_large: {
    type: 'house_large',
    name: 'Large House',
    width: 10,
    depth: 8,
    height: 5,
    hasInterior: true,
    entranceOffset: { x: 0, z: 4 },
    modelPath: HexTileAssets.UNIT_HOUSE,
  },
  outhouse: {
    type: 'outhouse',
    name: 'Outhouse',
    width: 1.5,
    depth: 1.5,
    height: 2.5,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0.75 },
    modelPath: null,
  },
  well: {
    type: 'well',
    name: 'Well',
    width: 2,
    depth: 2,
    height: 2,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0 },
    modelPath: StructureAssets.WELL,
  },
  fence: {
    type: 'fence',
    name: 'Fence',
    width: 4,
    depth: 0.2,
    height: 1.2,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0 },
    modelPath: StructureAssets.FENCE,
  },
  hitching_post: {
    type: 'hitching_post',
    name: 'Hitching Post',
    width: 2,
    depth: 0.5,
    height: 1,
    hasInterior: false,
    entranceOffset: { x: 0, z: 0 },
    modelPath: StructureAssets.RAIL,
  },
};
